services:
  
  pgdatabase:
  
    image: postgres:13
    
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi

    volumes:
      - "D://Data//courses//Data_Engineering_Zoomcamp//week_1//docker_sql//ny_taxi_postgers_data:/var/lib/postgresql/data:rw"
    
    ports:
      - "5432:5432" #localhost port : container port

    networks:
      - pg-network
    
  
  pgadmin:
    
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports: 
      - "8080:80"
    networks:
      - pg-network

  dbt:
    build: 
      
      context: .
      dockerfile: Dockerfile

    networks:
      - pg-network 
    
    entrypoint: ["tail", "-f", "/dev/null"]   

networks:
  pg-network:
     

     